In [118]:
import sklearn as sk
from patsy import dmatrices
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.lda import LDA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.qda import QDA
from matplotlib import pyplot as plt
%matplotlib inline

In [119]:
import numpy as np
import pandas as pd

In [120]:
df=pd.read_csv('/Users/Dhan/Downloads/Lab3/Default.csv')
df.default=np.where(df.default == "Yes", 1, 0)

In [121]:
y,X = dmatrices('default ~ income + balance', df, return_type = "dataframe")
y = np.ravel(y)
print y

[ 0.  0.  0. ...,  0.  0.  0.]


In [122]:
X_train= X[1:8001]
X_test=X[8002:]
y_train=y[1:8001]
y_test=y[8002:]
len(X_train)

8000

In [127]:
logit_1=LogisticRegression()
logit_1=logit_1.fit(X_train,y_train)
logit_1.score(X_train,y_train)

0.96650000000000003

In [100]:
logitpred=logit_1.predict(X_test)
print logitpred
confusion_matrix(y_test, logitpred)


[ 0.  0.  0. ...,  0.  0.  0.]


array([[1930,    1],
       [  67,    0]])

In [101]:
prob=logit_1.predict_proba(X_test)
print prob

[[  9.87932025e-01   1.20679750e-02]
 [  9.37338097e-01   6.26619031e-02]
 [  9.97550102e-01   2.44989816e-03]
 ..., 
 [  9.99141326e-01   8.58674288e-04]
 [  9.81761575e-01   1.82384254e-02]
 [  8.85699489e-01   1.14300511e-01]]


In [102]:
print metrics.accuracy_score(y_test,logitpred)

0.965965965966


In [103]:
lda1=LDA()
lda1=lda1.fit(X_train,y_train)
lda1.score(X_train,y_train)

0.97237499999999999

In [104]:
ldapredict=lda1.predict(X_test)
print ldapredict
confusion_matrix(y_test, ldapredict)


[ 0.  0.  0. ...,  0.  0.  0.]


array([[1928,    3],
       [  48,   19]])

In [105]:
print metrics.accuracy_score(y_test,ldapredict)

0.974474474474


In [106]:
knn1= KNeighborsClassifier(n_neighbors=2)
knn1=knn1.fit(X_train,y_train)
knn1.score(X_train,y_train)


0.97699999999999998

In [107]:
knnpredict=knn1.predict(X_test)
print knnpredict
confusion_matrix(y_test, knnpredict)

[ 0.  0.  0. ...,  0.  0.  0.]


array([[1928,    3],
       [  60,    7]])

In [108]:
print metrics.accuracy_score(y_test,knnpredict)

0.968468468468


In [109]:
knn2= KNeighborsClassifier(n_neighbors=10)
knn2=knn2.fit(X_train,y_train)
knn2.score(X_train,y_train)

0.96950000000000003

In [110]:
knnpredict1=knn2.predict(X_test)
print knnpredict1
confusion_matrix(y_test, knnpredict1)


[ 0.  0.  0. ...,  0.  0.  0.]


array([[1929,    2],
       [  63,    4]])

In [111]:
print metrics.accuracy_score(y_test,knnpredict1)

0.967467467467


In [112]:
qda1=QDA()
qda1=qda1.fit(X_train,y_train)
qda1.score(X_train,y_train)

0.96675

In [113]:
qdapredict=qda1.predict(X_test)
print qdapredict
confusion_matrix(y_test, qdapredict)



[ 0.  0.  0. ...,  0.  0.  0.]


array([[1931,    0],
       [  67,    0]])

In [117]:
print metrics.accuracy_score(y_test,qdapredict)

0.966466466466


In [115]:
# Strategies to improve the test accuarcy 
#We can do algorithm tuning Since machine learning algorithms are driven by parameters, these parameters will influence the outcome of learning.Objective of this is to find optimum value for each parameter to improve accuracy of the model. We should check the impact of each of these parameters on the model.
# By applying ensemble methods such as bagging and boosting we can improve the accuracy of the  model 

In [116]:
print metrics.accuracy_score(y_test,qdapredict)

0.966466466466
